name: Top GitHub Users

on:
  schedule:
    - cron: "0 0 * * *"   # mỗi ngày 00:00 UTC
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-22.04

    steps:
      - name: Show disk before cleanup
        run: df -h

      - name: Free disk space on runner
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true

      - name: Show disk after cleanup
        run: df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_TOKEN }}

      - name: Remove old generated data
        run: |
          rm -rf cache
          rm -rf docs

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: TOP GITHUB USERS ACTION
        uses: ePlus-DEV/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf cache
          rm -rf docs
          rm -rf node_modules
          rm -rf dist build .next .nuxt
